#!/usr/bin/env bash
# Write src/.env for the local run (dev tunnel behind APIM) from azd env values.
set -euo pipefail
cd "$(dirname "$0")/.."

ENV_VALUES="$(azd env get-values 2>/dev/null || true)"
v() { printf '%s\n' "$ENV_VALUES" | grep "^$1=" | head -1 | cut -d= -f2- | tr -d '"'; }

cat > src/.env <<EOF
CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTID=$(v DEV_BOT_APP_ID)
CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTSECRET=$(v DEV_BOT_APP_SECRET)
CONNECTIONS__SERVICE_CONNECTION__SETTINGS__TENANTID=$(v AZURE_TENANT_ID)
CONNECTIONS__SERVICE_CONNECTION__SETTINGS__AUTHTYPE=ClientSecret
AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__SSO__SETTINGS__AZUREBOTOAUTHCONNECTIONNAME=default_user_access_token
AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__SEARCH__SETTINGS__AZUREBOTOAUTHCONNECTIONNAME=search_access_token
CONNECTIONSMAP__0__CONNECTION=SERVICE_CONNECTION
CONNECTIONSMAP__0__SERVICEURL=*
BOT_CLIENT_ID=
MS_FOUNDRY_PROJECT_ENDPOINT=$(v FOUNDRY_PROJECT_ENDPOINT)
MS_FOUNDRY_ORCHESTRATOR_MODEL_DEPLOYMENT_NAME=$(v MS_FOUNDRY_ORCHESTRATOR_MODEL_DEPLOYMENT_NAME)
AZURE_SEARCH_ENDPOINT=$(v AZURE_SEARCH_ENDPOINT)
AZURE_SEARCH_INDEX=$(v AZURE_SEARCH_INDEX)
PORT=3978
EOF

echo "Wrote src/.env"
