#!/usr/bin/env bash
# Generate src/.env for the dev-tunnel-behind-APIM local run (Mode B).
# Pulls values from the current azd environment (provision outputs) and the dev bot
# secret created by provision_dev_bot.sh. The agent runs with full Bot Framework JWT
# validation + real SSO (the per-user search token carries your Entra group ACLs).
#
# Usage: ./scripts/gen_local_env.sh
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="src/.env"

command -v azd >/dev/null 2>&1 || { echo "ERROR: azd not found"; exit 1; }
get() { azd env get-value "$1" 2>/dev/null || true; }

DEV_BOT_APP_ID="$(get DEV_BOT_APP_ID)"
DEV_BOT_APP_SECRET="$(get DEV_BOT_APP_SECRET)"
TENANT_ID="$(get AZURE_TENANT_ID)"
FOUNDRY="$(get FOUNDRY_PROJECT_ENDPOINT)"
MODEL="$(get MS_FOUNDRY_ORCHESTRATOR_MODEL_DEPLOYMENT_NAME)"
SEARCH="$(get AZURE_SEARCH_ENDPOINT)"
SEARCH_INDEX="$(get AZURE_SEARCH_INDEX)"

[ -n "${DEV_BOT_APP_ID}" ]     || { echo "ERROR: DEV_BOT_APP_ID missing -> run ./scripts/provision_dev_bot.sh"; exit 1; }
[ -n "${DEV_BOT_APP_SECRET}" ] || { echo "ERROR: DEV_BOT_APP_SECRET missing -> run ./scripts/provision_dev_bot.sh"; exit 1; }
[ -n "${FOUNDRY}" ]            || { echo "ERROR: FOUNDRY_PROJECT_ENDPOINT missing -> run 'azd provision' first"; exit 1; }

cat > "${OUT}" <<EOF
# Generated by scripts/gen_local_env.sh -- Mode B (dev tunnel behind APIM).
# Full Bot Framework JWT validation + real SSO. Do not commit (see .gitignore).

# Single-tenant dev bot (Bot Connector auth via client secret)
CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTID=${DEV_BOT_APP_ID}
CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTSECRET=${DEV_BOT_APP_SECRET}
CONNECTIONS__SERVICE_CONNECTION__SETTINGS__TENANTID=${TENANT_ID}
CONNECTIONS__SERVICE_CONNECTION__SETTINGS__AUTHTYPE=ClientSecret

# SSO + per-user Search OAuth handlers (Bot Service OAuth connections)
AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__SSO__SETTINGS__AZUREBOTOAUTHCONNECTIONNAME=default_user_access_token
AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__SEARCH__SETTINGS__AZUREBOTOAUTHCONNECTIONNAME=search_access_token

# Connection map (required by the M365 Agents SDK)
CONNECTIONSMAP__0__CONNECTION=SERVICE_CONNECTION
CONNECTIONSMAP__0__SERVICEURL=*

# Foundry + Search data-plane use your 'az login' identity (BOT_CLIENT_ID empty).
BOT_CLIENT_ID=
MS_FOUNDRY_PROJECT_ENDPOINT=${FOUNDRY}
MS_FOUNDRY_ORCHESTRATOR_MODEL_DEPLOYMENT_NAME=${MODEL:-gpt-5.4}
AZURE_SEARCH_ENDPOINT=${SEARCH}
AZURE_SEARCH_INDEX=${SEARCH_INDEX:-secure-docs}

PORT=3978
EOF

echo "Wrote ${OUT} for Mode B (dev tunnel behind APIM)."
echo "Run it with:  cd src && uv run python main.py"
