# PowerShell backup of gen_local_env.sh (bash is the primary path).
# Generates src/.env for the dev-tunnel-behind-APIM local run (Mode B).
# Usage: ./scripts/gen_local_env.ps1
$ErrorActionPreference = "Stop"
Set-Location (Join-Path $PSScriptRoot "..")

if (-not (Get-Command azd -ErrorAction SilentlyContinue)) { Write-Error "azd not found"; exit 1 }
function Get-AzdValue($k) { return (azd env get-value $k 2>$null) }

$devBotId     = Get-AzdValue DEV_BOT_APP_ID
$devBotSecret = Get-AzdValue DEV_BOT_APP_SECRET
$tenantId     = Get-AzdValue AZURE_TENANT_ID
$foundry      = Get-AzdValue FOUNDRY_PROJECT_ENDPOINT
$model        = Get-AzdValue MS_FOUNDRY_ORCHESTRATOR_MODEL_DEPLOYMENT_NAME
$search       = Get-AzdValue AZURE_SEARCH_ENDPOINT
$searchIndex  = Get-AzdValue AZURE_SEARCH_INDEX

if (-not $devBotId)     { Write-Error "DEV_BOT_APP_ID missing -> run ./scripts/provision_dev_bot.ps1"; exit 1 }
if (-not $devBotSecret) { Write-Error "DEV_BOT_APP_SECRET missing -> run ./scripts/provision_dev_bot.ps1"; exit 1 }
if (-not $foundry)      { Write-Error "FOUNDRY_PROJECT_ENDPOINT missing -> run 'azd provision' first"; exit 1 }
if (-not $model)        { $model = "gpt-5.4" }
if (-not $searchIndex)  { $searchIndex = "secure-docs" }

@"
# Generated by scripts/gen_local_env.ps1 -- Mode B (dev tunnel behind APIM).
# Full Bot Framework JWT validation + real SSO. Do not commit (see .gitignore).

CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTID=$devBotId
CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTSECRET=$devBotSecret
CONNECTIONS__SERVICE_CONNECTION__SETTINGS__TENANTID=$tenantId
CONNECTIONS__SERVICE_CONNECTION__SETTINGS__AUTHTYPE=ClientSecret

AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__SSO__SETTINGS__AZUREBOTOAUTHCONNECTIONNAME=default_user_access_token
AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__SEARCH__SETTINGS__AZUREBOTOAUTHCONNECTIONNAME=search_access_token

CONNECTIONSMAP__0__CONNECTION=SERVICE_CONNECTION
CONNECTIONSMAP__0__SERVICEURL=*

BOT_CLIENT_ID=
MS_FOUNDRY_PROJECT_ENDPOINT=$foundry
MS_FOUNDRY_ORCHESTRATOR_MODEL_DEPLOYMENT_NAME=$model
AZURE_SEARCH_ENDPOINT=$search
AZURE_SEARCH_INDEX=$searchIndex

PORT=3978
"@ | Set-Content -Encoding utf8 "src/.env"

Write-Host "Wrote src/.env for Mode B (dev tunnel behind APIM)."
Write-Host "Run it with:  cd src; uv run python main.py"
